# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: |
       ./gradlew build
       tree
    # 通过 Dockerfile 构建镜像
    - name: Build docker image
      run: docker build . -t javademo:v1
    # 登陆到我的 docker registry
    - name: Login to tencent docker image registry
      run: |
        echo ${{ secrets.REGISTRY_USERNAME }}
        echo ${{ secrets.REGISTRY_PASSWORD }}
        echo "${{ secrets.REGISTRY_PASSWORD }}" |  docker login --username=${{ secrets.REGISTRY_USERNAME }}  ccr.ccs.tencentyun.com  --password-stdin


           
